services:

  db:
    image: mysql:8.0
    restart: always
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db:/var/lib/mysql/

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./html:/var/www/html
#      - ./html/wp-content:/var/www/html/wp-content
#      - ./html/wp-includes:/var/www/html/wp-includes
#      - ./html:/var/www/html/wp-config.php

volumes:
  db:
